name: pyspectrafuse
channels:
  - conda-forge
dependencies:
  - python>=3.8,<3.12
  - pip
  - numpy>=1.20.0
  - pandas>=1.3.0
  - pyarrow>=5.0.0
  - numba>=0.57
  - pip:
    - Click>=8.0.0
    - pyteomics>=4.5.0
    - spectrum_utils>=0.4.0
    - pytest>=7.0.0
    - pytest-cov>=4.0.0
    - pytest-mock>=3.10.0

